M48
; DRILL file {KiCad (6.0.10)} date Sun Apr 30 22:13:51 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-04-30T22:13:51+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0118
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T2C0.0197
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0394
%
G90
G05
T1
X5.61Y-4.38
T2
X5.27Y-4.84
T3
X4.52Y-4.6
X4.52Y-4.7
X4.52Y-4.8
X5.8524Y-4.3
X6.1476Y-4.3
T0
M30
