M48
; DRILL file {KiCad (6.0.10)} date Fri Mar 17 15:36:11 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-03-17T15:36:11+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0315
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0394
%
G90
G05
T1
X5.31Y-4.3
X5.34Y-4.44
X5.34Y-4.84
X5.71Y-4.3
T2
X4.52Y-4.6
X4.52Y-4.7
X4.52Y-4.8
X5.8524Y-4.3
X6.1476Y-4.3
T0
M30
